spring:
  redis:
    host: redis_test
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: everykafka:9098
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#logging:
#  level:
#    org.springframework.security: DEBUG
server:
  port: 9091

