spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
#logging:
#  level:
#    org.springframework.security: DEBUG
server:
  port: 9091
