
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: everykafka:9098
      group-id: productToOrder
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#logging:
#  level:
#    org.springframework.security: DEBUG
server:
  port: 9092

