spring:
  application:
    name: everyecommerce-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: nginx-member
          uri: http://nginx-member:90/
          predicates:
            - Path=/member-service/**
        - id: meber-service
          uri: http://member1:9081/
          predicates:
            - Path=/member-service2/**
        - id: product-service
          uri: http://product:9091/
          predicates:
            - Path=/product-service/**
        - id: order-service
          uri: http://order:7005/
          predicates:
            - Path=/order-service/**
server:
  port: 9002
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: TRACE
