spring:
  application:
    name: everyecommerce-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:90/
          predicates:
            - Path=/member-service/**
        - id: product-service
          uri: http://localhost:70/
          predicates:
            - Path=/product-service/**
server:
  port: 9001
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: TRACE
