version: '3'

services:
  application:
    container_name: product-service
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5002:9091"

  nginx:
    container_name: nginx2
    build: ./ci
    image: nginx:latest
    ports:
      - "70:70"
    depends_on:
      - application
